# base on latest python file
FROM python:latest

# add our python program
ADD run_master.py ./

# install dependent libraries
RUN pip install pika
RUN pip install uproot
RUN pip install numpy
RUN pip install matplotlib
RUN pip install awkward

# the command to run our program
CMD [ "python", "-u", "./run_master.py"]
