# base on latest python file
FROM python:latest

# install dependent libraries
# RUN pip install gzip
RUN pip install pika
RUN pip install uproot
RUN pip install numpy
RUN pip install matplotlib
RUN pip install awkward
RUN pip install requests
RUN pip install aiohttp

# add our python program
ADD infofile.py ./
ADD run_master.py ./

# the command to run our program
CMD [ "python", "-u", "./run_master.py"]
